reducer_config:
    shape_reducer_hdbscan:
        details:
            T0_tool4:
            - question_reducer
            - question_reducer
        shape: ellipse
        allow_single_cluster: True
        min_cluster_size: 4
        min_samples: 4
        metric_type: IoU
