reducer_config:
    shape_reducer_optics:
        details:
            T0_tool4:
            - question_reducer
            - question_reducer
        shape: ellipse
        allow_single_cluster: True
        min_cluster_size: 2
        min_samples: 2
        metric_type: IoU
